### ISSUE TITLE
Functional requirements and testing

### ISSUE THREAD

**Issue by michela** [georgekhut/moodLabVisuals#4]
I've transfered the scope of requirements doc into a spreadsheet to assist with signoff.

Please check you're happy with the scope (a few extras) and change "testing" to "done" once you've accepted delivery

https://docs.google.com/spreadsheets/d/16MjVBpAX_x2omtauLiucnfI5nr3fUIj0n9TkFvJfY04/edit#gid=0

**Comment by georgekhut** [comment]
Hi Michela, could you share that document to georgekhut@gmail.com

**Comment by michela** [comment]
Should be accessible now

**Comment by michela** [comment]
A few issues reverse engineering the effectors as it looks like the code for the dlls not provided (what links the lua code, shaders - maybe C++ codebase somewhere). Do you want me to request it or just leave it. It would be useful to have as reference but might be just as quick to just tweak the effects by eye with you on next session as most replicated now.

**Comment by georgekhut** [comment]
have updated the scope spreadsheet with comments re what's done/closed
