### ISSUE TITLE
test show displays with touch

### ISSUE THREAD

**Issue by michela** [georgekhut/moodLabVisuals#9]
Pls test test-layout.toe with your actual show hardware to confirm Touch resolution desired is correctly mapped.

I'll document how to switch the live show toe from 1 to 2 to 3 displays for dev purposes

**Comment by georgekhut** [comment]
Hi Michela
I've pulled from Git to the Zotac, but cant see "test-layout.toe" in the folder
I have the Zotac connected to the 3 55" Philips monitors, plus a
![screenshot 3](https://user-images.githubusercontent.com/5351109/29858617-9140a2dc-8da1-11e7-80ab-97db5488f03d.png)
 another smaller, control monitor.

**Comment by michela** [comment]
Sorry, added now.
